src/demo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('demo_auth.urls')),
    path('', include('demo_ui.urls')),
]

src/demo_api/urls.py
urlpatterns = []

src/demo_auth/urls.py
from django.urls import include, path
from .import views

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register_page, name='register'),
]

src/demo_ui/urls.py
from django.urls import path, re_path
from .views import IndexView

app_name = 'demo_ui'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    re_path(r'^.*$', IndexView.as_view())
]

src/demo_api/models.py
from django.db import models

# Create your models here.

src/demo_auth/models.py
# from django.contrib.auth.models import AbstractUser
#
#
# class User(AbstractUser):
#     pass

src/demo_ui/models.py
from django.db import models

# Create your models here.

src/demo_api/views.py
from django.shortcuts import render

# Create your views here.

src/demo_auth/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

def register_page(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')

    context = {'form': form}

    return render(request, 'registration/register.html', context)

src/demo_ui/views.py
from django.views.generic import TemplateView

# Create your views here.
class IndexView(TemplateView):
    template_name = 'demo_ui/index.html'

src/demo_ui/templates/base.html
{% load static %}
<!doctype html>

<html lang="en">
  <head>
    {% block head %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <link rel="shortcut icon" type="image/png" href="{% static 'img/favicon.ico' %}"/>
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,500;0,700;0,800;1,700&family=Roboto:wght@400;500;700;900&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="{% static 'css/main.css' %}" />
      {% block styles %}{% endblock %}
      <title>{% block title %}{% endblock %}</title>
    {% endblock %}
  </head>

  <body class="d-flex flex-column pt-0 min-vh-100 p-4">
    <div class="container-fluid">
      <header>
        {% include 'navbar.html' %}
      </header>

      <main>
        {% block content %}{% endblock %}
      </main>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
    {% block scripts %}{% endblock %}
  </body>

  <footer class="mt-auto p-4">
    <div class="container-fluid">
      <div class="row mb-md-3">
        <div class="align-self-center col-sm-12 col-md-6">
          <div>
            <span>Optional Information in Footer</span>
          </div>
        </div>
        <div class="align-self-center col-sm-12 col-md-6 py-lg-5 pt-5 p-md-0 text-end">
          <img src="{% static 'img/favicon.ico' %}" class="img-fluid" style="max-height: 36px" alt="Brought to you by Vue">
        </div>
      </div>
    </div>
  </footer>
</html>

src/demo_ui/templates/demo_ui/index.html
{% extends 'base.html' %}
{% load django_vite %}

{% block title %}Demo{% endblock %}

{% block content %}
  <div class="row">
    {% if user.is_authenticated %}
      <h1 class="mb-3">Demo</h1>
      <!-- Javascript disabled -->
      <noscript>
        <div class="card">
          <div class="card-body">
            <strong>
              We're sorry but the Demo tool doesn't work properly without JavaScript enabled. Please enable it to continue.
            </strong>
          </div>
        </div>
      </noscript>

      <!-- Javascript enabled, Vue SPA is bootstrapped here -->
      <div id="app"></div>
    {% else %}
      <div class="px-3">
        <div class="card px-4">
          <div class="card-body">
            <h1 class="display-5 fw-bold fs-2">Welcome to the Demo tool</h1>
            <hr />
            <a href="{{ LOGIN_URL }}" class="btn btn-primary" role="button">Log In</a>
            <a href="{{ REGISTER_URL }}" class="btn btn-primary" role="button">Register</a>
          </div>
        </div>
      </div>
    {% endif %}
  </div>
{% endblock %}

{% block scripts %}
  {% if user.is_authenticated %}
    <script id="csrf" type="application/json">""</script>
    {% if ga_measurement %}
      <script id="ga_measurement" type="application/json">""</script>
    {% endif %}
    <!-- Vite rendered JS -->
    {% vite_asset 'src/main.js' %}
  {% endif %}
{% endblock %}

src/demo_ui/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-md">
  <a class="navbar-brand" href="{% url 'demo_ui:index' %}">
    Home
  </a>
  <button class="navbar-toggler border rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarLinks" aria-controls="navbarLinks" aria-expanded="false" aria-label="Toggle navigation">
    <i class="bi bi-list" aria-hidden="true"></i>
  </button>

  <div class="collapse navbar-collapse" id="navbarLinks">
    {% if request.user.is_authenticated %}
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="d-block py-1 px-2 nav-link auth-link fw-normal" href="/"><i class="bi bi-person-fill pe-1" aria-hidden="true"></i>{{ request.user.get_full_name }}</a>
        </li>
        {% if request.user.is_staff %}
        <li class="nav-item">
          <a class="d-block py-1 px-2 nav-link auth-link fw-normal" href="{% url 'admin:index' %}"><i class="bi bi-shield-lock pe-1" aria-hidden="true"></i>Admin</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <form class="form-inline" action="{{ LOGOUT_URL }}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn nav-link auth-link fw-normal py-1 px-2">
              <i class="bi bi-door-closed pe-1" aria-hidden="true"></i>Log Out
            </button>
          </form>
        </li>
      </ul>
      {% else %}
        <ul class="navbar-nav ms-auto">
          <li class="nav-item">
            <a href="{{ LOGIN_URL }}" class="nav-link auth-link fw-normal">
              <i class="bi bi-door-open pe-1" aria-hidden="true"></i>Log In
            </a>
          </li>
        </ul>
      {% endif %}
    </ul>
  </div>
</nav>